/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhao_algorithmMagic_algorithm_OperationAlgorithmManager */

#ifndef _Included_zhao_algorithmMagic_algorithm_OperationAlgorithmManager
#define _Included_zhao_algorithmMagic_algorithm_OperationAlgorithmManager
#ifdef __cplusplus
extern "C" {
#endif
#undef zhao_algorithmMagic_algorithm_OperationAlgorithmManager_VERSION
#define zhao_algorithmMagic_algorithm_OperationAlgorithmManager_VERSION 1.14f
#undef zhao_algorithmMagic_algorithm_OperationAlgorithmManager_PrintCalculationComponentLog
#define zhao_algorithmMagic_algorithm_OperationAlgorithmManager_PrintCalculationComponentLog 0L
/*
 * Class:     zhao_algorithmMagic_algorithm_OperationAlgorithmManager
 * Method:    getAlgorithmStarUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zhao_algorithmMagic_algorithm_OperationAlgorithmManager_getAlgorithmStarUrl
        (JNIEnv *, jclass);

/*
 * Class:     zhao_algorithmMagic_algorithm_OperationAlgorithmManager
 * Method:    getAlgorithmMemoryAddress
 * Signature: (Lzhao/algorithmMagic/algorithm/OperationAlgorithm;)J
 */
JNIEXPORT jlong JNICALL Java_zhao_algorithmMagic_algorithm_OperationAlgorithmManager_getAlgorithmMemoryAddress
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
